name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python src/main.py

      - name: Configure Git user identity
        run: |
          git config --global user.email "zichunwang733@gmail.com"
          git config --global user.name "chun77"

      - name: Generate summary report and commit
        run: |
          python src/main.py
          git add output/summary_report.md output/total_medals_by_top_50_countries.png
          if ! git diff --cached --quiet; then
            git commit -m "Add summary report for all countries and data visualization for top 50 countries"
            git push
          else
            echo "No changes to commit"
          fi
